### ISSUE TITLE
Doesn't work with split panes

### ISSUE THREAD

**Issue by bbailleux** [liujingbreak/atom-js-grammar#2]
When using more that one panel (e.g. `View` > `Panes` > `Split Right`), the viewer always appears in the left pane, not the currently active one.
Further more (don't know if it is related), it doesn't show when the short-cut (default: `<Ctrl>F12`) is used, and the user must use the mouse to dig into the `Packages` menu.

Note: when a file with only one _ES6 class_ and some methods are defined, the viewer stay empty.

**Comment by liujingbreak** [comment]
Thanks for pointing out issues.
I have been using Visual Code recently, so it is out of maintenance, but I will spend some time to fix it. 
#3

**Comment by liujingbreak** [comment]
Fixed ES6 class issue along with supporting JSX file by replacing parser engine with acorn-jsx.
But I can't reproduce `short-cut (default: <Ctrl>F12)` issue on my mac, I am guess probable cause might be:
- If one editor area has not be focused yet,  shortcut key pressing will not be captured.
- Ctrl-12 is hijacked by operating system at somewhere.

Fixed split panes.

But now it will not hide automatically, must require explicitly press ctrl/cmd + F12 or ESC to hide.
